name: Terraform Workflow

on:
  push:
    branches:
      - main
      - upload

jobs:
  terraform-upload:
    name: Terraform Apply - Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies w/ ci
        run: npm ci
        working-directory: my_tech_blog

      - name: Find build directory
        run: find . -type d -name build  # Find where the build directory is created

      - name: Build app
        run:  npm run build
        working-directory: my_tech_blog
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          REACT_APP_S3_IMG_URL: ${{ secrets.REACT_APP_S3_IMG_URL }} # Using the secret in the environment

      # Initialize Terraform for the "upload" environment
      - name: Terraform Init
        working-directory: terraform/upload
        run: terraform init

      # Plan Terraform changes for the "upload" environment
      - name: Terraform Plan
        working-directory: terraform/upload
        run: terraform plan

      # Apply Terraform changes for the "upload" environment
      - name: Terraform Apply
        working-directory: terraform/upload
        run: terraform apply -auto-approve
    
      # Verify deletion
      - name: List bucket contents after deletion
        run: aws s3 ls s3://brynnpark-tech-blog --recursive
